name: build

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Add micromamba to system path
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-name: sai
        environment-file: build-env.yaml
    - name: Test with pytest
      run: |
        micromamba run -n sai pip install -e .
        micromamba run -n sai pytest --cov=. --cov-report term-missing -vv
        micromamba run -n sai coverage xml
    - name: upload coverage report to codecov
      uses: codecov/codecov-action@v4
      with:
          name: codecov-umbrella
          fail_ci_if_error: true
          env_vars: OS,PYTHON
          token: ${{ secrets.CODECOV_TOKEN }}
